CREATE TABLE LASTROOM (
userId CHAR(5) NOT NULL,
roomId CHAR(5) NOT NULL,
PRIMARY KEY(userId,roomId),
FOREIGN KEY(userID) REFERENCES USERS(userId),
FOREIGN KEY(roomID) REFERENCES ROOMS(roomId)
);

INSERT INTO LASTROOM (USERID,ROOMID) VALUES('U0000','R0000');
INSERT INTO LASTROOM (USERID,ROOMID) VALUES('U0001','R0000');
INSERT INTO LASTROOM (USERID,ROOMID) VALUES('U0002','R0000');
INSERT INTO LASTROOM (USERID,ROOMID) VALUES('U0003','R0000');
INSERT INTO LASTROOM (USERID,ROOMID) VALUES('U0004','R0000');